#!/usr/bin/env bash
# Regenerates squarespace/ deploy targets from src/ source files.
# Run this after any edit to src/.
#
# Usage:  ./build.sh
set -euo pipefail
cd "$(dirname "$0")"

echo "▸ Copying CSS..."
cp src/styles.css squarespace/custom-css.css
echo "  ✓ squarespace/custom-css.css"

echo "▸ Bundling homepage Code Block..."
python3 - << 'PY'
from pathlib import Path
import re

root = Path('.')
homepage = (root / 'src' / 'homepage.html').read_text()

# Grab body content only
body_match = re.search(r'<body>([\s\S]*?)</body>', homepage)
if not body_match:
    raise SystemExit("ERROR: <body> not found in src/homepage.html")
body = body_match.group(1).strip()

# Strip sections between SQUARESPACE-STRIP markers (nav and footer).
# These are delivered separately via Code Injection and footer block.
body = re.sub(r'<!-- SQUARESPACE-STRIP-START: \w+ -->[\s\S]*?<!-- SQUARESPACE-STRIP-END: \w+ -->\s*', '', body)

# Strip external <script src="..."> refs — we'll inline them below
body = re.sub(r'<script src="[^"]+"></script>\s*', '', body)
# Also strip external <link rel="stylesheet"> refs — CSS lives in Custom CSS panel
body = re.sub(r'<link rel="stylesheet" href="[^"]+">\s*', '', body)

# Concatenate all JS (order matters: data files first, then scripts.js)
inline_js = '\n\n'.join([
    (root / 'src' / 'data' / 'coaches.js').read_text().rstrip(),
    (root / 'src' / 'data' / 'schedule.js').read_text().rstrip(),
    (root / 'src' / 'data' / 'programs.js').read_text().rstrip(),
    (root / 'src' / 'data' / 'reviews.js').read_text().rstrip(),
    (root / 'src' / 'scripts.js').read_text().rstrip(),
])

# Append as a single inlined <script> block
body_with_js = body + '\n\n<script>\n' + inline_js + '\n</script>\n'

header = """<!--
  ============================================================
  SQUARESPACE CODE BLOCK — HOMEPAGE
  ============================================================
  Auto-generated by build.sh. Do not hand-edit this file.
  Source: /src/homepage.html + /src/data/*.js + /src/scripts.js

  Where this goes:
    Homepage → Edit → Add Section → Code Block
    Paste the ENTIRE contents of this file (excluding this comment).

  Companion files (must also be installed):
    - squarespace/custom-css.css       → Design → Custom CSS
    - squarespace/header-injection.html → Settings → Code Injection → Header
    - squarespace/nav-injection.html   → Settings → Code Injection → Footer
    - squarespace/footer-block.html    → Footer → editable HTML block
  ============================================================
-->

"""

(root / 'squarespace' / 'homepage-code-block.html').write_text(header + body_with_js)
size_kb = len(header + body_with_js) // 1024
print(f"  ✓ squarespace/homepage-code-block.html ({size_kb} KB)")
PY

echo ""
echo "Done. Next: paste the changed files into Squarespace per squarespace/README.md"
