# build.ps1 — regenerates squarespace/ deploy targets from src/
# Windows PowerShell equivalent of build.sh.
#
# Usage:  .\build.ps1
#
# If PowerShell blocks the script, run this once in an admin terminal:
#   Set-ExecutionPolicy -ExecutionPolicy RemoteSigned -Scope CurrentUser

$ErrorActionPreference = "Stop"
Set-Location $PSScriptRoot

Write-Host "> Copying CSS..." -ForegroundColor Cyan
Copy-Item -Path "src\styles.css" -Destination "squarespace\custom-css.css" -Force
Write-Host "  [OK] squarespace\custom-css.css" -ForegroundColor Green

Write-Host "> Bundling homepage Code Block..." -ForegroundColor Cyan

# Read source files
$homepage      = Get-Content -Raw -Path "src\homepage.html"
$coaches       = Get-Content -Raw -Path "src\data\coaches.js"
$schedule      = Get-Content -Raw -Path "src\data\schedule.js"
$programs      = Get-Content -Raw -Path "src\data\programs.js"
$reviews       = Get-Content -Raw -Path "src\data\reviews.js"
$scriptsMain   = Get-Content -Raw -Path "src\scripts.js"

# Extract <body>...</body> content only
if ($homepage -match "(?s)<body>(.*?)</body>") {
    $body = $matches[1].Trim()
} else {
    throw "ERROR: <body> tag not found in src\homepage.html"
}

# Strip sections between SQUARESPACE-STRIP markers (nav and footer)
# These are delivered separately via Code Injection and footer block.
$body = $body -replace '(?s)<!-- SQUARESPACE-STRIP-START: \w+ -->.*?<!-- SQUARESPACE-STRIP-END: \w+ -->\s*', ''

# Strip external <script src="..."> tags — they'll be inlined below
$body = $body -replace '<script src="[^"]+"></script>\s*', ''
# Strip external <link rel="stylesheet"> tags — CSS lives in Custom CSS panel
$body = $body -replace '<link rel="stylesheet" href="[^"]+">\s*', ''

# Concatenate all JS in order (data files first, then scripts.js)
$inlineJs = @($coaches.TrimEnd(), $schedule.TrimEnd(), $programs.TrimEnd(), $reviews.TrimEnd(), $scriptsMain.TrimEnd()) -join "`n`n"

# Append as a single inlined <script> block at the end
$bodyWithJs = $body + "`n`n<script>`n" + $inlineJs + "`n</script>`n"

$header = @"
<!--
  ============================================================
  SQUARESPACE CODE BLOCK - HOMEPAGE
  ============================================================
  Auto-generated by build.ps1. Do not hand-edit this file.
  Source: /src/homepage.html + /src/data/*.js + /src/scripts.js

  Where this goes:
    Homepage -> Edit -> Add Section -> Code Block
    Paste the ENTIRE contents of this file (excluding this comment).

  Companion files (must also be installed):
    - squarespace/custom-css.css       -> Design -> Custom CSS
    - squarespace/header-injection.html -> Settings -> Code Injection -> Header
    - squarespace/nav-injection.html   -> Settings -> Code Injection -> Footer
    - squarespace/footer-block.html    -> Footer -> editable HTML block
  ============================================================
-->


"@

$output = $header + $bodyWithJs
Set-Content -Path "squarespace\homepage-code-block.html" -Value $output -NoNewline

$sizeKb = [math]::Round(($output.Length / 1024), 1)
Write-Host "  [OK] squarespace\homepage-code-block.html ($sizeKb KB)" -ForegroundColor Green

Write-Host ""
Write-Host "Done. Next: paste the changed files into Squarespace per squarespace\README.md" -ForegroundColor Yellow
